language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - python setup.py install
script:
  - cd tests
  - python -m unittest discover --verbose --start-directory .
  - cd ..
before_deploy:
  - . version.sh
  - python setup.py sdist
deploy:
  provider: pypi
  user: $DEPLOY_PYPI_USER
  password: $DEPLOY_PYPI_PASS
  skip_existing: true
  on:
    condition: $TRAVIS_BRANCH =~ release-.*
