language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - python setup.py install
script:
  - cd tests
  - python -m unittest discover --verbose --start-directory .
  - cd ..
before_deploy:
  - export VERSION_NUMBER=$(echo $RID | cut -d'v' -f 2).$TRAVIS_BUILD_NUMBER
  - sed -i -e 's/0\.0\.0/'"$VERSION_NUMBER"'/g' setup.py
  - python setup.py sdist
deploy:
  provider: pypi
  user: $DEPLOY_PYPI_USER
  password: $DEPLOY_PYPI_PASS
  skip_existing: true
  on:
    tags: true
    condition: "$TRAVIS_TAG == release-*"
